#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=gpushort
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=8GB
#SBATCH --job-name=inverse_render

ml CUDA/10.2.89-GCC-8.3.0
ml Python/3.7.4-GCCcore-8.3.0

source /data/s2576597/SGAN/venv/bin/activate

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/1fb07d5bf3421a46e2b83b21c9537e1b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/inference_1fb07d5bf3421a46e2b83b21c9537e1b_1_view
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/3d908c2b4f5812702fc668af6d3ad0ad/ --num_frames=128 --image_size=128 --output_dir=inverse_images/inference_3d908c2b4f5812702fc668af6d3ad0ad_1_view
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/50c0bd9933f7259fe59358c5e6239c84/ --num_frames=128 --image_size=128 --output_dir=inverse_images/inference_50c0bd9933f7259fe59358c5e6239c84_1_view

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/1fb07d5bf3421a46e2b83b21c9537e1b/ --num_frames=128 --image_size=128 --n_input_views=2 --output_dir=inverse_images/inference_1fb07d5bf3421a46e2b83b21c9537e1b_2_view
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/3d908c2b4f5812702fc668af6d3ad0ad/ --num_frames=128 --image_size=128 --n_input_views=2 --output_dir=inverse_images/inference_3d908c2b4f5812702fc668af6d3ad0ad_2_view
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/50c0bd9933f7259fe59358c5e6239c84/ --num_frames=128 --image_size=128 --n_input_views=2 --output_dir=inverse_images/inference_50c0bd9933f7259fe59358c5e6239c84_2_view
