#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=gpushort
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=8GB
#SBATCH --job-name=inverse_render

ml CUDA/10.2.89-GCC-8.3.0
ml Python/3.7.4-GCCcore-8.3.0

source /data/s2576597/SGAN/venv/bin/activate

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_no_opt_lock/1b1a7af332f8f154487edd538b3d83f6/
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_no_opt_lock/1c3c8952b92d567e61c6c61410fc904b/
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_no_opt_lock/1cb95c00d3bf6a3a58dbdf2b5c6acfca/
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_no_opt_lock/1f7393970917e558b4a20251cec15600/

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_2view/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_2view/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_2view/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/no_mirror/cars_inference_2view/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1b1a7af332f8f154487edd538b3d83f6/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1c3c8952b92d567e61c6c61410fc904b/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1cb95c00d3bf6a3a58dbdf2b5c6acfca/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1f7393970917e558b4a20251cec15600/
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/1fb07d5bf3421a46e2b83b21c9537e1b/ --num_frames=128 --image_size=104 --n_input_views=3 --output_dir=inverse_images/inference_1fb07d5bf3421a46e2b83b21c9537e1b_3_view
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/3d908c2b4f5812702fc668af6d3ad0ad/ --num_frames=128 --image_size=104 --n_input_views=3 --output_dir=inverse_images/inference_3d908c2b4f5812702fc668af6d3ad0ad_3_view
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/inference_poses/50c0bd9933f7259fe59358c5e6239c84/ --num_frames=128 --image_size=104 --n_input_views=3 --output_dir=inverse_images/inference_50c0bd9933f7259fe59358c5e6239c84_3_view
