#!/bin/bash

#SBATCH --time=02:00:00
#SBATCH --partition=gpushort
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=8GB
#SBATCH --job-name=inverse_render

ml CUDA/10.2.89-GCC-8.3.0
ml Python/3.7.4-GCCcore-8.3.0

source /data/s2576597/SGAN/venv/bin/activate

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_sym_loss_hierarchical_v2/generator.pth inverse_images/ships/1fb07d5bf3421a46e2b83b21c9537e1b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/1fb07d5bf3421a46e2b83b21c9537e1b/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_sym_loss_hierarchical_v2/generator.pth inverse_images/ships/3d908c2b4f5812702fc668af6d3ad0ad/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/3d908c2b4f5812702fc668af6d3ad0ad/ --use_view_lock_for_optimization
CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_sym_loss_hierarchical_v2/generator.pth inverse_images/ships/50c0bd9933f7259fe59358c5e6239c84/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/50c0bd9933f7259fe59358c5e6239c84/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_sym_loss_hierarchical_v2/generator.pth inverse_images/ships/container/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/container/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_sym_loss_hierarchical_v2/generator.pth inverse_images/ships/yamato/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/yamato/ --use_view_lock_for_optimization
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_no_mirror_v2/30--06:22--_99000--generator.pth inverse_images/ships/container/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/no_mirror/container/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetships_no_mirror_v2/30--06:22--_99000--generator.pth inverse_images/ships/yamato/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/no_mirror/yamato/ --use_view_lock_for_optimization


#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/real_images/minicooper/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/real/cars_inference/minicooper/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/real_images/mustang/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/real/cars_inference/mustang/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/real_images/minicooper/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/real/no_mirror/cars_inference/minicooper/ --use_view_lock_for_optimization --change_yaw
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/real_images/mustang/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/real/no_mirror/cars_inference/mustang/ --use_view_lock_for_optimization --change_yaw

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/rapide/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/cars_inference/rapide/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/peugot/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/cars_inference/peugot/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/minicooper/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/cars_inference/minicooper/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/pickup/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/cars_inference/pickup/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/rapide/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/no_mirror/cars_inference/rapide/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/peugot/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/no_mirror/cars_inference/peugot/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/minicooper/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/no_mirror/cars_inference/minicooper/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_no_mirror/21--22:03--generator.pth inverse_images/cars/pickup/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l2/no_mirror/cars_inference/pickup/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/rapide/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/rapide/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/peugot/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/peugot/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/minicooper/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/minicooper/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth inverse_images/cars/pickup/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/pickup/
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/generator.pth inverse_images/cars/rapide/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/rapide/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/generator.pth inverse_images/cars/peugot/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/peugot/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/generator.pth inverse_images/cars/minicooper/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/minicooper/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/generator.pth inverse_images/cars/pickup/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/pickup/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1b1a7af332f8f154487edd538b3d83f6/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1c3c8952b92d567e61c6c61410fc904b/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1cb95c00d3bf6a3a58dbdf2b5c6acfca/
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference_no_opt_lock/1f7393970917e558b4a20251cec15600/
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=128 --output_dir=inverse_images/l1/white_back/cars_inference/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization
#
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1b1a7af332f8f154487edd538b3d83f6/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1b1a7af332f8f154487edd538b3d83f6/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1c3c8952b92d567e61c6c61410fc904b/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1c3c8952b92d567e61c6c61410fc904b/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1cb95c00d3bf6a3a58dbdf2b5c6acfca/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py sncars_sym_loss_hier_generator.pth inverse_images/cars/1f7393970917e558b4a20251cec15600/ --num_frames=128 --image_size=104 --n_input_views=2 --output_dir=inverse_images/l1/white_back/cars_inference_2view/1f7393970917e558b4a20251cec15600/ --use_view_lock_for_optimization

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/ships/1fb07d5bf3421a46e2b83b21c9537e1b/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/1fb07d5bf3421a46e2b83b21c9537e1b/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/ships/3d908c2b4f5812702fc668af6d3ad0ad/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/3d908c2b4f5812702fc668af6d3ad0ad/ --use_view_lock_for_optimization
#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_final_result.py good_generator_hier_sym_loss.pth inverse_images/ships/50c0bd9933f7259fe59358c5e6239c84/ --num_frames=128 --image_size=128 --output_dir=inverse_images/ships_inference/50c0bd9933f7259fe59358c5e6239c84/ --use_view_lock_for_optimization
