#!/bin/bash

#SBATCH --time=71:30:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=32GB
#SBATCH --job-name=sgan_shapenet

ml CUDA/10.2.89-GCC-8.3.0
ml Python/3.7.4-GCCcore-8.3.0

source /data/s2576597/SGAN/venv/bin/activate

CUDA_VISIBLE_DEVICES=0 python -u train.py --output_dir=/data/s2576597/SGAN/shapenetship --curriculum=SPATIALSIRENBASELINELBSHIP --load_dir=/data/s2576597/SGAN/shapenetship
