#!/bin/bash

#SBATCH --time=71:30:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=16GB
#SBATCH --job-name=syn_ds

ml CUDA/10.2.89-GCC-8.3.0
ml Python/3.7.4-GCCcore-8.3.0

source /data/s2576597/SGAN/venv/bin/activate

CUDA_VISIBLE_DEVICES=0 python -u inverse_render_dataset_creation.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth /scratch/s2576597/new_view_synthesis_datasets/car_view_synthesis_test_set/ --output_dir /scratch/s2576597/new_view_synthesis_datasets/car_view_synthesis_test_set_output_no_view_lock_at_all_700/ --image_size 128 --n_iterations=700

#CUDA_VISIBLE_DEVICES=0 python -u inverse_render_dataset_creation.py /data/s2576597/SGAN/shapenetcars_sym_loss_hierarchical/17--20:36--generator.pth /scratch/s2576597/new_view_synthesis_datasets/car_view_synthesis_test_set/ --output_dir /scratch/s2576597/new_view_synthesis_datasets/car_view_synthesis_test_set_output/ --image_size 128 --use_view_lock_for_optimization --n_iterations=700
